name: flutter_modularized_di

sdkPath: .fvm/flutter_sdk

packages:
  - app
  - packages/**

ide:
  intellij:
    enabled: false

command:
  clean:
    hooks:
      post: melos exec rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./ios/Podfile.lock ./.dart_tool ./pubspec.lock

  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.22.2"

    dependencies:
      flutter_bloc: ^8.1.4
      shared_preferences: ^2.2.2
      provider: ^6.1.2

    dev_dependencies:
      flutter_lints: ^4.0.0
      lints: ^4.0.0

# This _diff scripts belows will not work as intended until the following
# feature is implemented https://github.com/invertase/melos/pull/702.
scripts:
  analyze: melos exec dart analyze .

  analyze_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents \
      dart analyze .

  format_check_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents \
      dart format . --set-exit-if-changed

  format_check: melos exec dart format . --set-exit-if-changed

  test_unit_with_coverage_package:
    run: melos exec MELOS_ROOT_PATH/scripts/test_with_coverage.sh --exclude-tags golden
    packageFilters:
      dirExists:
        - test

  test_unit_package_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents \
      flutter test --exclude-tags golden
    packageFilters:
      dirExists:
        - test

  test_unit_with_coverage: melos run test_unit_with_coverage_package --no-select

  test_unit_diff: melos run test_unit_package_diff --no-select

  test_golden_package:
    run: melos exec flutter test --tags golden --dart-define=CI=true
    packageFilters:
      dirExists:
        - test
      dependsOn:
        - alchemist

  test_golden_package_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents \
      flutter test --tags golden --dart-define=CI=true
    packageFilters:
      dirExists:
        - test
      dependsOn:
        - alchemist

  test_golden: melos run test_golden_package --no-select

  test_golden_diff: melos run test_golden_package_diff --no-select

  update_goldens:
    run: melos exec flutter test --update-goldens
    packageFilters:
      dependsOn:
        - alchemist
