name: presentation
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cross_cutting_concerns:
    path: ../cross_cutting_concerns
  domain:
    path: ../domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  provider: ^6.1.2

dev_dependencies:
  alchemist: ^0.7.0
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
