name: domain
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_cutting_concerns:
    path: ../cross_cutting_concerns

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.4
